## 题目一：两个有序数列的中位数

### 思路1：分别定义两个指针，等两个和为(m+n)/2时，即为中位数。

复杂度为O(m+n)

同理可推广到两个有序数列第k小的数。

In [20]:
def find_medien(arr1, arr2):
    if len(arr_1) == 0 and len(arr_2) == 0:
        return None
    p1 = 0
    p2 = 0
    mid = (len(arr1) + len(arr2))//2
    i = 0
    while i <= mid:
        if p1 < len(arr_1) and p2 < len(arr_2):
            if arr1[p1] <= arr2[p2]:
                p1 += 1
            else:
                p2 += 1
        elif p1 > len(arr_1):
            p2 += 1
        else:
            p1 += 1
        i += 1
    if p1 < len(arr_1) and p2 < len(arr_2):    
        return max(arr1[p1], arr2[p2])
    elif p1 >= len(arr_1):
        return arr_2[p2]
    else:
        return arr_1[p1]

In [23]:
import numpy as np
arr_1 = np.arange(1, 6, 2)
print(arr_1)
arr_2 = np.arange(1, 21, 2)
print(arr_2)
print(find_medien(arr_1, arr_2))
print()

arr_1 = []
arr_2 = []
print(find_medien(arr_1, arr_2))

print()
arr_1 = []
arr_2 = np.arange(1, 21, 2)
print(arr_2)
print(find_medien(arr_1, arr_2))

[1 3 5]
[ 1  3  5  7  9 11 13 15 17 19]
7

None

[ 1  3  5  7  9 11 13 15 17 19]
11


### 思路2：折半查找

详细思路参考：https://www.cnblogs.com/TenosDoIt/p/3554479.html

复杂度为O(log(m+n))